apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: consul-server-2
  name: consul-server-2
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: consul-server-2
    spec:
      containers:
      - args:
        - agent
        - -server
        - -retry-join
        - consul-server-bootstrap
        - -client
        - 0.0.0.0
        image: philipdexter/consul-dev:latest
        name: consul-server-2
        resources: {}
      restartPolicy: Always
status: {}
